version: "3.9"

services:
  php:
    image: composer:2.3
    tty: true
    volumes:
      - "${PWD}:/app2/"
    command: bash
    depends_on:
      - mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
